export const ShoeData = [
    {
        id:"1",
        url:"https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/h/i/t/-original-imagg5wccdgd4k9m.jpeg?q=70",
        name:"Mountaineer"
    },
    {
        id:"2",
        url:"https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/f/w/k/10-es-21-grey-10-clymb-grey-original-imah2gasskenghpw.jpeg?q=70",
        name:"Villager"
    },
    {
        id:"3",
        url:"https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/r/e/m/-original-imagsfdvuffvqx4x.jpeg?q=70",
        name:"Cycler"
    },
    {
        id:"4",
        url:"https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/v/5/j/-original-imah2c3pfbxdgpcc.jpeg?q=70",
        name:"Engineer"
    }
]